pipeline {
    agent {
        docker{
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparation') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd api && rspec'
            }
        }
        stage('UAT'){
            steps{
                echo 'Aguardando Testes de Aceitação'
                input message: 'Podemos ir para produção'
            }
        }
        stage('Produção'){
            steps{
                echo 'API pronta para produção'
            }
        }
    }
    post{
        always{
            junit 'api/logs/report.xml'
        }
    }
}
