require "digest/md5"

require_relative "features/support/libs/mongo.rb"

def to_md5(pass)
  return Digest::MD5.hexdigest(pass)
end

task :test do
  puts "Exevutando um código Rake"
end

task :local_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/local.yml"))
  users = [
    { name: "Jeremias Araújo", email: "jqcaraujo@hotmail.com", password: to_md5("pwd123") },
    { name: "Roberto Carlos", email: "rei@yahoo.com", password: to_md5("pwd123") },
    { name: "Anderson Silva", email: "spider@uol.com", password: to_md5("pwd123") },
  ]

  #Zerando a base e inserindo os 5 usuários da lista, para obter sucesso na execução dos testes
  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  sh "cucumber"
end

task :hmg_seeds do
  CONFIG = YAML.load_file(File.join(Dir.pwd, "features/support/config/hmg.yml"))
  users = [
    { name: "Jeremias Araújo", email: "jqcaraujo@hotmail.com", password: to_md5("pwd123") },
    { name: "Roberto Carlos", email: "rei@yahoo.com", password: to_md5("pwd123") },
    { name: "Anderson Silva", email: "spider@uol.com", password: to_md5("pwd123") },
  ]

  #Zerando a base e inserindo os 5 usuários da lista, para obter sucesso na execução dos testes
  MongoDB.new.drop_danger
  MongoDB.new.insert_users(users)

  #sh "cucumber"
end
